**Matrix Multiplication**
# we will use tf.matmul() method
**Rule**
1. Inner dimension must match
  (m,n)@(n,p)
  eg.
  (5,7)@(8,9) It will not work bc n are diff
  (5,8)@(8,9) will work bc same inner demension.
2. The result matrix has the shape of outer demension.
meaning
A(m,n)
B(n,p)
so result has (m,p)
eg.
(4,7)@(7,5) ->(4,5)

In [1]:
import tensorflow as tf
import numpy as np

In [5]:
tensor_A=tf.constant([[1,2],[3,4],[4,5]],dtype=tf.int32)
tensor_B=tf.constant([[5,6],[7,8]],dtype=tf.int32)
print("Shape of A",tensor_A.shape)
print("Shape of B",tensor_B.shape)

Shape of A (3, 2)
Shape of B (2, 2)


In [7]:
tensor_C=tf.matmul(tensor_A,tensor_B)
print(tensor_C)
print("Shape of C",tensor_C.shape)

tf.Tensor(
[[19 22]
 [43 50]
 [55 64]], shape=(3, 2), dtype=int32)
Shape of C (3, 2)


In [9]:
X=tf.constant([
               [1.,0.,-1.],
               [2.,3.,1.]
               ],
              dtype=tf.float32)
X


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  0., -1.],
       [ 2.,  3.,  1.]], dtype=float32)>

In [10]:
Y=tf.constant([
               [4.],
               [5.],
               [6.]
               ],
              dtype=tf.float32)
Y

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [11]:
print("X Shape",X.shape)
print("Y Shape",Y.shape)

X Shape (2, 3)
Y Shape (3, 1)


In [12]:
Z=tf.matmul(X,Y)
print(Z)
print("Z Shape",Z.shape)

tf.Tensor(
[[-2.]
 [29.]], shape=(2, 1), dtype=float32)
Z Shape (2, 1)


In [15]:
print(f'X-Shape : {X.shape},Y-Shape : {Y.shape}, Z-Shape : {Z.shape}')
print(X.numpy)
print(Y.numpy)
print(Z.numpy)

X-Shape : (2, 3),Y-Shape : (3, 1), Z-Shape : (2, 1)
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  0., -1.],
       [ 2.,  3.,  1.]], dtype=float32)>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-2.],
       [29.]], dtype=float32)>>


Transpose : Transpose swaps axes. For 2D matrix shape (m,n) become (n,m) after transpose

In [21]:
tensor_one = tf.constant([[[1,2],[2,3]],[[4,5],[6,7]]],
                         dtype=tf.int32)
print(tensor_one)
print("Shape of tensor_one",tensor_one.shape)

tf.Tensor(
[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]], shape=(2, 2, 2), dtype=int32)
Shape of tensor_one (2, 2, 2)


In [23]:
tensor_one_transpose=tf.transpose(tensor_one)
print(tensor_one_transpose)
print("Shape Tensor One Transpose",tensor_one_transpose.shape)

tf.Tensor(
[[[1 4]
  [2 6]]

 [[2 5]
  [3 7]]], shape=(2, 2, 2), dtype=int32)
Shape Tensor One Transpose (2, 2, 2)


In [26]:
# 3D Transpose with explicit axis permutation
tensor_two=tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    ],dtype=tf.int32)
print(tensor_two)



tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [29]:
#swap first and last axes (0,1,2)->(0,2,1)
t2_transpose=tf.transpose(tensor_two,perm=[0,2,1])
print(t2_transpose)
print("Shape of t2_transpose",t2_transpose.shape)
print("Shape of tensor_two",tensor_two.shape)

tf.Tensor(
[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]], shape=(2, 2, 2), dtype=int32)
Shape of t2_transpose (2, 2, 2)
Shape of tensor_two (2, 2, 2)


**Reshape**
# tf.reshape(tensor,new_shape)
# change the shape without changing the data.
**Rule** The total number of elements must stay the same

In [30]:
tensor=tf.constant([
                    [1,2,3],
                    [4,5,6]
                    ],dtype=tf.int32)
print(tensor)
print("Shape of tensor",tensor.shape)
print("Total number of elements in tensor",
      tf.size(tensor).numpy())


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape of tensor (2, 3)
Total number of elements in tensor 6


In [38]:
tensor_r2=tf.reshape(tensor,[1,6])
print(tensor_r2)
print("Shape of tensor_r2",tensor_r2.shape)
print("Total number of elements in tensor_r2 are :",
      tf.size(tensor_r2).numpy())

tf.Tensor([[1 2 3 4 5 6]], shape=(1, 6), dtype=int32)
Shape of tensor_r2 (1, 6)
Total number of elements in tensor_r2 are : 6


In [39]:
tensor_r3=tf.reshape(tensor,[6,1])
print(tensor_r3)
print("Shape of tensor_r3",tensor_r3.shape)
print("Total number of elements in tensor_r3 are :",
      tf.size(tensor_r3).numpy())

tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]], shape=(6, 1), dtype=int32)
Shape of tensor_r3 (6, 1)
Total number of elements in tensor_r3 are : 6


In [43]:
#infer dimension
tensor_r4=tf.reshape(tensor,shape=[-1,2])
print(tensor_r4)
print("Shape of tensor_r4",tensor_r4.shape)
print("Total number of elements in tensor_r4 are :",
      tf.size(tensor_r4).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor_r4 (3, 2)
Total number of elements in tensor_r4 are : 6


In [45]:
#Task : Reshape (2,6) -> (3,4) and (1,12)
tensor_given = tf.constant([[1,2,3,4,5,6],[7,8,9,10,11,12]],dtype=tf.int32)
print(tensor_given)
print("Shape of tensor_given",tensor_given.shape)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)
Shape of tensor_given (2, 6)


In [46]:
tensor34=tf.reshape(tensor_given,shape=[3,4])
print(tensor34)
print("Shape of tensor34",tensor34.shape)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
Shape of tensor34 (3, 4)


In [48]:
tensor112=tf.reshape(tensor_given,[1,12])
print(tensor112)

tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)
