we are going to start TensorFlow Basics here

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.19.0


In [ ]:
#Creatint Tensor with constant
#function here that we can use to create
# 0D Scalar
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
# 1D Vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# 2D Matrix
second_matrix=tf.constant([[5,7],[3,8],[3,9],[4,2],[8,6]],dtype=tf.int16)
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int16, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int16)>

In [ ]:
# 3D Tensor of Matrices
third_matrix=tf.constant(
    [
        [[1,2,3],
        [2,4,5]],
        [[7,9,3],
         [10,4,5]],
        [[11,2,3],
         [2,4,15]]
    ]
)
third_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [ ]:
#single number that mean scalar
second_matrix=tf.constant([[5,7],[3,8],[3,9],[4,2],[8,6]],dtype=tf.float32)


In [ ]:
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
# a number with direction
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#a 2-D array of numbers
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
#Tensor : an n-dimensional array
tensor=tf.constant([[[1,2],[3,4],],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
#Finds the shape, rank and size of the tensors
print("scalar Information")
print("Shape:",scalar.shape)
print("Dimension:",scalar.ndim)
print("Rank :", tf.rank(scalar).numpy())
print("Size :", tf.size(scalar))


scalar Information
Shape: ()
Dimension: 0
Rank : 0
Size : tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print("Vector Information")
print("Shape:",vector.shape)
print("Dimension:",vector.ndim)
print("Rank :", tf.rank(vector).numpy())
print("Size :", tf.size(vector))

Vector Information
Shape: (2,)
Dimension: 1
Rank : 1
Size : tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
print("Matrix Information")
print("Shape:",matrix.shape)
print("Dimension:",matrix.ndim)
print("Rank :", tf.rank(matrix).numpy())
print("Size :", tf.size(matrix))

Matrix Information
Shape: (2, 2)
Dimension: 2
Rank : 2
Size : tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
print("Tensor Information")
print("Shape:",tensor.shape)
print("Dimension:",tensor.ndim)
print("Rank :", tf.rank(tensor).numpy())
print("Size :", tf.size(tensor))

Tensor Information
Shape: (2, 2, 2)
Dimension: 3
Rank : 3
Size : tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
#Creating Tensor using variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [ ]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [ ]:
# Will become error,because you cannot change constant tensor.(unchangeable)
# unchangeable_tensor[0].assign(12)
# unchangeable_tensor

Random Tensor

In [ ]:
# Random Tensor
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.21193933, 0.6076282 , 0.6753261 , ..., 0.05822587, 0.9717059 ,
        0.7576902 ],
       [0.00910461, 0.36007917, 0.5479208 , ..., 0.7900033 , 0.68072975,
        0.69750094],
       [0.9816562 , 0.26300573, 0.80418456, ..., 0.44760132, 0.8815365 ,
        0.7901037 ],
       ...,
       [0.89386237, 0.3438884 , 0.00169373, ..., 0.775223  , 0.70940304,
        0.504637  ],
       [0.9745958 , 0.57985246, 0.15590978, ..., 0.91193247, 0.9682685 ,
        0.7673377 ],
       [0.86802244, 0.48957407, 0.23606145, ..., 0.22750866, 0.96517694,
        0.34212828]], dtype=float32)>

In [ ]:
#same seed, same tensor
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [ ]:
#diff seed, diff tensor
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(15)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [ ]:
#creating Tensors using zeroes
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [ ]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#creating Tensors all ones
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones


<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [ ]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [ ]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [ ]:
print("Tensor Information")
print("Shape:",tensor_numpy.shape)
print("Dimension:",tensor_numpy.ndim)
print("Rank :", tf.rank(tensor_numpy).numpy())
print("Size :", tf.size(tensor_numpy))
print("DataType of elements : ",tensor_numpy.dtype)
print("Elements along axis 0 : ",tensor_numpy.shape[0])
print("Elements along axis 1 : ",tensor_numpy.shape[1])
print("Elements along axis 2 : ",tensor_numpy.shape[2])
print("Total numbers of element : ",tf.size(tensor_numpy).numpy())

Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Rank : 3
Size : tf.Tensor(24, shape=(), dtype=int32)
DataType of elements :  <dtype: 'int16'>
Elements along axis 0 :  2
Elements along axis 1 :  3
Elements along axis 2 :  4
Total numbers of element :  24


In [ ]:
# Working with item of each dimension
# First threeelements
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [ ]:
# First two elements of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

** Arthmetic Operations with Tensors **
+Add
+Sub
+Multiply
+Div

In [ ]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [ ]:
#tensor_one+15
tf.add(tensor_one,15)    #also can use this

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [ ]:
# tensor_one-5
tf.subtract(tensor_one,5)   #also can use this

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [ ]:
# tensor_one*2
tf.multiply(tensor_one,2)   #also can use this

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [ ]:
# tensor_one/2
tf.divide(tensor_one,2)   #also can use this

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [ ]:
second_matrix=tf.constant([[8,16],[64,8.25],[625,9.23],[125,2.34],[169,144]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.25]
 [625.     9.23]
 [125.     2.34]
 [169.   144.  ]], shape=(5, 2), dtype=float32)


In [ ]:
#Squareroot only work on float dtype
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

Exercise

In [ ]:
random_tensor_ex=tf.random.uniform(shape=(6,300),minval=0,maxval=1)
random_tensor_ex

<tf.Tensor: shape=(6, 300), dtype=float32, numpy=
array([[0.35069752, 0.77278566, 0.00380659, ..., 0.30103004, 0.32508636,
        0.8619559 ],
       [0.43442726, 0.69141364, 0.38343132, ..., 0.04173088, 0.04454041,
        0.51802087],
       [0.781891  , 0.6432277 , 0.20477164, ..., 0.23425353, 0.4298755 ,
        0.10339081],
       [0.2613392 , 0.45418906, 0.66810894, ..., 0.8241252 , 0.00892866,
        0.591359  ],
       [0.841298  , 0.23048604, 0.2378087 , ..., 0.0604229 , 0.3619542 ,
        0.9485799 ],
       [0.6955091 , 0.19503939, 0.84378576, ..., 0.21378493, 0.04226327,
        0.79853487]], dtype=float32)>

In [ ]:
print("Tensor Information")
print("Shape:",random_tensor_ex.shape)
print("Dimension:",random_tensor_ex.ndim)
print("Rank :", tf.rank(random_tensor_ex).numpy())
print("Size :", tf.size(random_tensor_ex))
print("Total numbers of element : ",tf.size(random_tensor_ex).numpy())

Tensor Information
Shape: (6, 300)
Dimension: 2
Rank : 2
Size : tf.Tensor(1800, shape=(), dtype=int32)
Total numbers of element :  1800


In [ ]:
random_tensor_ex2=tf.random.uniform(shape=(6,300),minval=0,maxval=1)
random_tensor_ex2

<tf.Tensor: shape=(6, 300), dtype=float32, numpy=
array([[0.66634464, 0.02056229, 0.993775  , ..., 0.3600564 , 0.3030311 ,
        0.93501914],
       [0.08400691, 0.6860635 , 0.5224252 , ..., 0.5122007 , 0.08689892,
        0.51010036],
       [0.3352393 , 0.28681898, 0.45636106, ..., 0.9372524 , 0.81474614,
        0.8590797 ],
       [0.2303375 , 0.9456861 , 0.39651525, ..., 0.267362  , 0.26527202,
        0.08688903],
       [0.70438397, 0.37282598, 0.1109314 , ..., 0.3792597 , 0.25232124,
        0.91345847],
       [0.36589658, 0.25833333, 0.18328893, ..., 0.470165  , 0.2419405 ,
        0.6370386 ]], dtype=float32)>

In [ ]:
print("Tensor Information")
print("Shape:",random_tensor_ex2.shape)
print("Dimension:",random_tensor_ex2.ndim)
print("Rank :", tf.rank(random_tensor_ex2).numpy())
print("Size :", tf.size(random_tensor_ex2))
print("Total numbers of element : ",tf.size(random_tensor_ex2).numpy())

Tensor Information
Shape: (6, 300)
Dimension: 2
Rank : 2
Size : tf.Tensor(1800, shape=(), dtype=int32)
Total numbers of element :  1800
