**We are going to discuss NLP Basics here**


*   NLP pipeline




In [46]:
# import required libraries
# NLTK is Naturel Language Tool Kit
import nltk
import spacy
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import re
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd
# import string
# import warnings
# warnings.filterwarnings('ignore')

In [47]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [48]:
our_text="Artifical Intelligence and Machine Learning are going to change the future of technology!"

In [49]:
#split text into individual words/token
tokens=nltk.word_tokenize(our_text)
tokens

['Artifical',
 'Intelligence',
 'and',
 'Machine',
 'Learning',
 'are',
 'going',
 'to',
 'change',
 'the',
 'future',
 'of',
 'technology',
 '!']

In [50]:
# cleaning tokens
clean_tokens = [re.sub(r'[^a-zA-Z]', '', token.lower()) for token in tokens if token.isalpha()]
# clean_tokens = [token.lower() for token in tokens if token.isalpha()]  # <- same result
clean_tokens

['artifical',
 'intelligence',
 'and',
 'machine',
 'learning',
 'are',
 'going',
 'to',
 'change',
 'the',
 'future',
 'of',
 'technology']

In [51]:
# Stop words Removal
stop_words = set(stopwords.words('english'))
filtered_tokens = [token for token in clean_tokens if token not in stop_words]
# Removes common less meaningful words
filtered_tokens

['artifical',
 'intelligence',
 'machine',
 'learning',
 'going',
 'change',
 'future',
 'technology']

In [52]:
#Steaming
stemmer = PorterStemmer()
stemmed_tokens = [stemmer.stem(token) for token in filtered_tokens]
#Reduce the words to their root form (not always a word from dictionary)
stemmed_tokens

['artif', 'intellig', 'machin', 'learn', 'go', 'chang', 'futur', 'technolog']

In [53]:
# Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]
# convert words to their dictonary form (lemma) using POS : part of speech
lemmatized_tokens

['artifical',
 'intelligence',
 'machine',
 'learning',
 'going',
 'change',
 'future',
 'technology']

Bag of words(BOW)

In [54]:
corpus = ["Artificial Intelligence is transforming inductries",
          "Machine Learning is a branch of Artificial Intelligence",
          "Deep Larning is a subfield of Machine Learning",
          "Natural Language Processing is a subfield of Artificial Intelligence"]

In [56]:
CV = CountVectorizer()
bow_matrix = CV.fit_transform(corpus)
print("BOW Matrix Array")
print(bow_matrix.toarray())
print("Feature Name BOW")
print(CV.get_feature_names_out())

BOW Matrix Array
[[1 0 0 1 1 1 0 0 0 0 0 0 0 0 1]
 [1 1 0 0 1 1 0 0 1 1 0 1 0 0 0]
 [0 0 1 0 0 1 0 1 1 1 0 1 0 1 0]
 [1 0 0 0 1 1 1 0 0 0 1 1 1 1 0]]
Feature Name BOW
['artificial' 'branch' 'deep' 'inductries' 'intelligence' 'is' 'language'
 'larning' 'learning' 'machine' 'natural' 'of' 'processing' 'subfield'
 'transforming']
