# Numpy Introduction an Usage

## we will use Numpy in this Jupyter Notebook

### One Dimentional Array (1-D)

In [6]:
import numpy as np

In [7]:
array1=np.array([10,20,30,40,50])

In [8]:
array1  #or can use print(array1)

array([10, 20, 30, 40, 50])

### Two Dimentional Array (2-D)

In [11]:
array_d2=np.array([[10,20,30],[40,50,60]])

In [13]:
print(array_d2)

[[10 20 30]
 [40 50 60]]


### Three Dimentional Array (3-D)

In [15]:
array_d3=np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])

In [16]:
print(array_d3)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


### Find out Dimension of Numpy Array

In [17]:
print('First Array Dimension :\t',array1.ndim)


First Array Dimension :	 1


In [18]:
print('Second Array Dimension :\t',array_d2.ndim)

Second Array Dimension :	 2


In [19]:
print('Third Array Dimension :\t',array_d3.ndim)

Third Array Dimension :	 3


# write an array of 5 students mark using Numpy
    ## Marks are : 80, 70, 75, 99, 89

In [20]:
studentsmark=np.array([80,70,75,99,89])

In [ ]:
print('students Marks :