In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel('students.xlsx')
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   Nick   21     59
5  Nancy   20     90


In [7]:
marks=df['Marks'].to_numpy()
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 59 90]


In [8]:
print('Highest Marks', np.max(marks))

Highest Marks 92


In [9]:
print('Lowest Marks', np.min(marks))

Lowest Marks 59


In [10]:
print('Average Marks', np.mean(marks))

Average Marks 82.33333333333333


## .loc :label Based
## .iloc : index Based

In [24]:
print('Original Dataframe')
print(df)
print('Location : Label Based')
print(df.loc[4])
print(df.loc[4,['Name','Age']])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   Nick   21     59
5  Nancy   20     90
Location : Label Based
Name     Nick
Age        21
Marks      59
Name: 4, dtype: object
Name    Nick
Age       21
Name: 4, dtype: object
Name     Nick
Marks      59
Name: 4, dtype: object


In [21]:
print('Original Dataframe')
print(df)
print('Location : Index Based')
print(df.iloc[4])
print(df.iloc[4,[0,2]])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   Nick   21     59
5  Nancy   20     90
Location : Index Based
Name     Nick
Age        21
Marks      59
Name: 4, dtype: object
Name     Nick
Marks      59
Name: 4, dtype: object


## Axis in Numpy : 
#### 1.Axis 0 : Vertical direction- work column-wise
#### 2.Axis 1 : Horizontal direction- work row-wise

We have 2 students marks in 3 subjects
[[45,50,49],[30,45,49]]

In [27]:
marks_arr=np.array([[45,50,49],[30,45,49]])
print(marks_arr)

[[45 50 49]
 [30 45 49]]


In [29]:
print('sum down each column',np.sum(marks_arr, axis=0))

sum down each column [75 95 98]


In [30]:
print('sum down each column',np.sum(marks_arr, axis=1))

sum down each column [144 124]


In [31]:
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 59 90]


#### find the student Name who got highest marks

In [35]:
topper=df.loc[df['Marks'].idxmax(),'Name']
print('Top Student Name :',topper)

Top Student Name : Sara


In [36]:
lowest=df.loc[df['Marks'].idxmin(),'Name']
print('Top Student Name :',lowest)

Top Student Name : Nick


In [41]:
highest=df.iloc[df['Marks'].idxmax(),0]
print('Top Student Name :',highest)

Top Student Name : Sara


In [39]:
bottom=df.iloc[df['Marks'].idxmin(),0]
print('Top Student Name :',bottom)

Top Student Name : Nick


In [42]:
print('Next Example iloc')

Next Example iloc


In [ ]:
top_index=df['Marks'].idxmax()
top_student=df.iloc[top_index,df.columns.get_loc('Name')]
print('Top of the Class is : ',top_student)

AttributeError: 'int' object has no attribute 'df'