# Numpy Introduction an Usage

## we will use Numpy in this Jupyter Notebook

### One Dimentional Array (1-D)

In [2]:
import numpy as np

In [3]:
array1=np.array([10,20,30,40,50,60,70])

In [4]:
array1  #or can use print(array1)

array([10, 20, 30, 40, 50, 60, 70])

In [5]:
print(array1)

[10 20 30 40 50 60 70]


### Two Dimentional Array (2-D)

In [11]:
array_d2=np.array([[10,20,30],[40,50,60]])

In [13]:
print(array_d2)

[[10 20 30]
 [40 50 60]]


### Three Dimentional Array (3-D)

In [15]:
array_d3=np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])

In [16]:
print(array_d3)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


### Find out Dimension of Numpy Array

In [17]:
print('First Array Dimension :\t',array1.ndim)


First Array Dimension :	 1


In [18]:
print('Second Array Dimension :\t',array_d2.ndim)

Second Array Dimension :	 2


In [19]:
print('Third Array Dimension :\t',array_d3.ndim)

Third Array Dimension :	 3


# write an array of 5 students mark using Numpy

##    Marks are : 80, 70, 75, 99, 89

In [20]:
studentsmark=np.array([80,70,75,99,89])

In [22]:
print('student Marks : ',studentsmark)

student Marks :  [80 70 75 99 89]


## Write an array : to take marks of 5 Students in 3 subjects using Numpy

### Math, English, Chemistry

[[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]]

In [24]:
markssubject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])

In [26]:
print('2-D Array Example')
print(markssubject)

2-D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


### Write an array : to take marks of 4 Students in 3 subjects for 2 semester using Numpy
#### students Name are: 'Anuar','Najib','Mahathir','Sabri' 
#### Math, English, Chemistry
#### Two Semester: Sem1, Sem2
##### 4*3*2
##### [[[85,88],[78,82],[42,45]],[[85,88],[78,82],[42,45]],[[85,88],[78,82],[90,95]],[[85,88],[78,82],[70,90]]]

In [31]:
marks_sub_sem=np.array([[[85,88],[78,82],[42,45]],
                        [[85,88],[78,82],[42,45]],
                        [[85,88],[78,82],[90,95]],
                        [[85,88],[78,82],[70,90]]])

In [32]:
print('Marks for Semester subject\n',marks_sub_sem)

Marks for Semester subject
 [[[85 88]
  [78 82]
  [42 45]]

 [[85 88]
  [78 82]
  [42 45]]

 [[85 88]
  [78 82]
  [90 95]]

 [[85 88]
  [78 82]
  [70 90]]]


## Write an array : to take wheater of 2 cities in 3 days for three times in a Day Morning, Noon, Evening. using Numpy
### City Names are: Kuala Lumpur, Delhi
### Days : Saturday, Sunday, Monday
### Three Time Slot : Morning , Noon , Evening

In [6]:
wheater_array=np.array([[[28,26],[34,39],[37,40]],[[25,22],[36,36],[35,36]],[[28,25],[39,37],[38,39]]])

In [7]:
print('Weather In 2 city KL and Delhi for 3 days\n(Saturday, sunday, Monday) during Morning,Noon,Evening')

Weather In 2 city KL and Delhi for 3 days
(Saturday, sunday, Monday) during Morning,Noon,Evening


In [8]:
print(wheater_array)

[[[28 26]
  [34 39]
  [37 40]]

 [[25 22]
  [36 36]
  [35 36]]

 [[28 25]
  [39 37]
  [38 39]]]


In [10]:
print('Size of Weather : ',wheater_array.size)

Size of Weather :  18


In [11]:
print('Shape of Weather : ',wheater_array.shape)

Shape of Weather :  (3, 3, 2)


In [12]:
print('Dimension of Weather : ',wheater_array.ndim)

Dimension of Weather :  3


In [13]:
print('Data Type of Weather : ',wheater_array.dtype)

Data Type of Weather :  int64


### Basic Info
#### Size : Numbers of elements
#### Shape : Rows and Columns
#### Dimension : return dimention 1,2,3 ....
#### Data Type : return stored data values type

In [52]:
print(array1)

[10 20 30 40 50]


In [55]:
print('Size of Array1 : ',array1.size)

Shape of Array1 :  5


In [56]:
print('Shape of Array1 : ',array1.shape)

Shape of Array1 :  (5,)


In [57]:
print('Dimension of Array1 : ',array1.ndim)

Shape of Array1 :  1


In [58]:
print('Data Type of Array1 : ',array1.dtype)

Data Type of Array1 :  int64


#### Students 

In [81]:
student_array=np.array(['Abdul Rahman','Hussien Onn', 'Abdul Razak','Mahatdhir','Abdullah'])

In [82]:
print(student_array)

['Abdul Rahman' 'Hussien Onn' 'Abdul Razak' 'Mahatdhir' 'Abdullah']


In [83]:
print('Shape : ',student_array.shape)

Shape :  (5,)


In [84]:
print('Size : ',student_array.size)

Size :  5


In [85]:
print('Dimension : ',student_array.ndim)

Dimension :  1


In [86]:
print('Data Type : ',student_array.dtype)

Data Type :  <U12


# Mathematical Operation

In [90]:
print(array1)

[10 20 30 40 50 60 70]


In [91]:
total=np.sum(array1)

In [92]:
print(total)

280


In [93]:
print('Mean :',np.mean(array1))

Mean : 40.0


In [94]:
print('Min :',np.min(array1))

Min : 10


In [95]:
print('Max :',np.max(array1))

Max : 70


In [96]:
print('index of Min :',np.argmin(array1))

index of Min : 0


In [97]:
print('index of Max :',np.argmax(array1))

index of Max : 6


#### Searching and Sorting Example in 1-d Array

In [131]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])

In [132]:
#print(np.argmax(our_arr))

In [133]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


In [134]:
sorted_arr=np.sort(our_arr)
print("sorted Arry: ")
print(sorted_arr)

sorted Arry: 
[ 100  200  300  300  400  500  600 1900 7000]


In [135]:
print('Is there any item greater than 500? :',np.any(sorted_arr>500))

Is there any item greater than 500? : True


In [136]:
print('All greater than 500? :',np.where(sorted_arr>500))

All greater than 500? : (array([6, 7, 8]),)


In [140]:
print('All Numbers greater than 500')
for num in np.where(sorted_arr>500):
    print(num)

All Numbers greater than 500
[6 7 8]


In [156]:
print(np.argmax(sorted_arr))

8


In [157]:
selected_values=sorted_arr[sorted_arr>500]

In [158]:
print(selected_values)

[ 600 1900 7000]


In [159]:
for num in selected_values:
    print(num)

600
1900
7000


In [160]:
for num in sorted_arr[sorted_arr>500]:
    print(num)

600
1900
7000


In [161]:
print(' ',sorted_arr[sorted_arr>500])

  [ 600 1900 7000]


## Slicing 1-D array
    1. to take elements from starting index to end index
    2. e.g.[start:end]

In [162]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


In [165]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [163]:
slice_our_arr=our_arr[1:4]
print(slice_our_arr)

[ 200  300 7000]


## Starting from an index and going till last
    ## [start:end]


In [164]:
print(our_arr[3:])

[7000  400  500  300 1900  600]


In [171]:
print(our_arr[:3])

[100 200 300]


In [169]:
print(sorted_arr[:7])

[100 200 300 300 400 500 600]


In [172]:
print(sorted_arr[5:])

[ 500  600 1900 7000]


In [170]:
print(our_arr[:7])

[ 100  200  300 7000  400  500  300]


## Step
    ## [start:end:step]
    ## step:every step element


In [173]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[200 300 500]


In [176]:
print('Original Arry')
print(sorted_arr)
print('Every Third Element')
every_third_element=sorted_arr[::3]
print(every_third_element)

Original Arry
[ 100  200  300  300  400  500  600 1900 7000]
Every Third Element
[100 300 600]


### Slice Reverse

In [177]:
print('Original Arry')
print(sorted_arr)
print('Reversel Arry : ')
print(sorted_arr[::-1])

Original Arry
[ 100  200  300  300  400  500  600 1900 7000]
Reversel Arry : 
[7000 1900  600  500  400  300  300  200  100]


In [179]:
print('Last Five Elements : ')
print(sorted_arr[-5:])

Last Five Elements : 
[ 400  500  600 1900 7000]


In [180]:
print('Slicing Done')

Slicing Done
